# Generated by Django 3.1 on 2020-08-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(default='The Safest Way to Pay', max_length=60)),
                ('HeaderQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('AboutUsTitle', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('AboutUsQuot', models.CharField(default='Lorem ipsum dolor sit amet.', max_length=100)),
                ('AboutUsList', models.JSONField(default='{}', max_length=100)),
                ('BuyerQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('SellerQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('SecureTitle', models.CharField(default='SAFE & SECURE & NO ADVANCE PAYMENT RISK', max_length=100)),
                ('SecureQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('TrusTitle', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('TrustQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('SupportTitle', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('SupportQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('TestimonialsQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
                ('FooterQuot', models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='RayBim Tech.', max_length=30)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='RayBim Tech.', max_length=30)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Tovfikur Rahman', max_length=30)),
                ('Rank', models.CharField(default='Developer', max_length=20)),
                ('Quot', models.CharField(default='Lunch is not free', max_length=100)),
            ],
        ),
    ]
