# Generated by Django 3.1 on 2020-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='AboutUsList',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='index',
            name='AboutUsQuot',
            field=models.TextField(default='Lorem ipsum dolor sit amet.', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='AboutUsTitle',
            field=models.CharField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=60),
        ),
        migrations.AlterField(
            model_name='index',
            name='BuyerQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='FooterQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=300),
        ),
        migrations.AlterField(
            model_name='index',
            name='HeaderQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='SecureQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='SellerQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='SupportQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='TestimonialsQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='TrustQuot',
            field=models.TextField(default="Lorem Ipsum is text industry. Ipsum has been the industry's standard dummy text. Lorem Ipsum is simply dummy text of the printing.", max_length=200),
        ),
    ]
