# Generated by Django 3.1 on 2020-08-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200814_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quot', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='index',
            name='AboutUsList',
        ),
        migrations.AddField(
            model_name='index',
            name='AboutUsList',
            field=models.ManyToManyField(blank=True, null=True, to='website.AboutUsList'),
        ),
    ]
