# Generated by Django 3.1 on 2020-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200814_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='AboutUsList',
            field=models.ManyToManyField(blank=True, to='website.AboutUsList'),
        ),
    ]
