# Generated by Django 3.1 on 2020-08-08 17:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash', models.IntegerField(default=0)),
                ('TotalTransfer', models.IntegerField(default=0)),
                ('TotalWithdraw', models.IntegerField(default=0)),
                ('LastActive', models.DateTimeField(auto_now_add=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CashInHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(default='+8801796693300', max_length=128, region=None)),
                ('Amount', models.IntegerField(default=0)),
                ('TrxId', models.CharField(max_length=64)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.walletdetails')),
            ],
        ),
    ]
