# Generated by Django 3.0.8 on 2020-07-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_cash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='CashHistory',
        ),
    ]
