# Generated by Django 3.0.8 on 2020-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20200729_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhistory',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
