# Generated by Django 3.0.8 on 2020-07-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20200729_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinhistory',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.WalletDetails'),
        ),
    ]
