# Generated by Django 3.0.8 on 2020-07-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20200730_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinhistory',
            name='userId',
        ),
    ]
