# Generated by Django 3.0.8 on 2020-07-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_cashinhistory_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinhistory',
            name='TrxId',
            field=models.CharField(max_length=64),
        ),
    ]
