# Generated by Django 3.0.8 on 2020-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20200730_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletdetails',
            old_name='TotalTransection',
            new_name='TotalTransfer',
        ),
    ]
