# Generated by Django 3.0.8 on 2020-07-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrXid', models.CharField(max_length=64)),
                ('Chk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiddlewareDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CashDirection', models.BooleanField(default=False)),
                ('FixedCash', models.IntegerField(default=None)),
                ('Times', models.DateTimeField(auto_now_add=True)),
                ('pin', models.IntegerField(default=None)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails')),
            ],
        ),
    ]
