# Generated by Django 3.1 on 2020-08-08 17:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(default='+8801796693300', max_length=128, region=None)),
                ('Amount', models.IntegerField(default=0)),
                ('TrxId', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FixedCash', models.IntegerField(default=None)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('Product', models.BooleanField(default=True)),
                ('Title', models.CharField(default='Write a TITLE', max_length=50)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('BuyerWalletId', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Buyer_of_this_transection', to='user.userdetails')),
                ('Creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Creator_of_this_transaction', to='user.userdetails')),
                ('SellerWalletId', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Seller_of_this_transection', to='user.userdetails')),
            ],
        ),
    ]
