# Generated by Django 3.0.8 on 2020-07-29 08:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8801796693300', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='cash',
            name='TrXid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
