# Generated by Django 3.1 on 2020-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ExtraText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
