# Generated by Django 3.0.8 on 2020-07-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_auto_20200729_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='TrXid',
            new_name='TrxId',
        ),
    ]
