# Generated by Django 3.1 on 2020-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_transaction_extratext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeOfTransection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
    ]
