# Generated by Django 3.0.8 on 2020-07-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_auto_20200729_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='Chk',
        ),
    ]
