# Generated by Django 3.1 on 2020-08-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('middleware', '0003_feeoftransection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FixedCash', models.IntegerField(default=None)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('Product', models.BooleanField(default=True)),
                ('Title', models.CharField(default='Write a TITLE', max_length=50)),
                ('ExtraText', models.TextField(blank=True, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('BuyerWalletId', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trash_Buyer_of_this_transection', to='user.userdetails')),
                ('Creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trash_Creator_of_this_transaction', to='user.userdetails')),
                ('SellerWalletId', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trash_Seller_of_this_transection', to='user.userdetails')),
            ],
        ),
    ]
