# Generated by Django 3.1 on 2020-08-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('middleware', '0004_transactiontrash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontrash',
            name='BuyerWalletId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trash_6Buyer_of_this_transection', to='user.userdetails'),
        ),
    ]
