# Generated by Django 3.0.8 on 2020-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0004_remove_cash_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
