# Generated by Django 3.0.8 on 2020-07-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0006_auto_20200730_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seler',
            new_name='Seller',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='SelerId',
            new_name='SellerId',
        ),
    ]
