# Generated by Django 3.0.8 on 2020-07-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0007_auto_20200730_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiddlewareDetails',
        ),
    ]
