# Generated by Django 3.0.8 on 2020-07-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200730_0435'),
        ('middleware', '0008_delete_middlewaredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='SellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='BuyerId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails'),
        ),
    ]
