# Generated by Django 3.0.8 on 2020-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0009_auto_20200730_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerWalletId', models.IntegerField()),
                ('BuyerWalletId', models.IntegerField()),
                ('FixedCash', models.IntegerField(default=None)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='BuyerId',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
