# Generated by Django 3.0.8 on 2020-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0010_auto_20200730_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='BuyerWalletId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transection',
            name='SellerWalletId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
