# Generated by Django 3.0.8 on 2020-07-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0012_auto_20200730_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transection',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='transection',
            index_together={('SellerWalletId', 'BuyerWalletId')},
        ),
    ]
