# Generated by Django 3.0.8 on 2020-07-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0013_auto_20200730_1756'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transection',
            index_together=set(),
        ),
    ]
