# Generated by Django 3.0.8 on 2020-07-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0014_auto_20200730_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
