# Generated by Django 3.0.8 on 2020-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0015_transection_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerWalletId', models.IntegerField(blank=True, null=True)),
                ('BuyerWalletId', models.IntegerField(blank=True, null=True)),
                ('FixedCash', models.IntegerField(default=None)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('Product', models.BooleanField(default=True)),
                ('Image1', models.ImageField(upload_to='')),
                ('Image2', models.ImageField(upload_to='')),
                ('Image3', models.ImageField(blank=True, upload_to='')),
                ('Image4', models.ImageField(blank=True, upload_to='')),
                ('Image5', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Transection',
        ),
    ]
