# Generated by Django 3.0.8 on 2020-08-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200801_0941'),
        ('middleware', '0016_auto_20200802_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Creator_of_this_transaction', to='user.UserDetails'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Title',
            field=models.CharField(default='Write a TITLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='BuyerWalletId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Buyer_of_this_transection', to='user.UserDetails'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='SellerWalletId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Seller_of_this_transection', to='user.UserDetails'),
        ),
    ]
