# Generated by Django 3.0.8 on 2020-08-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20200803_1759'),
        ('middleware', '0017_auto_20200803_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.Chat'),
        ),
    ]
