# Generated by Django 3.0.8 on 2020-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20200804_1817'),
        ('middleware', '0018_transaction_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Chat',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Chat',
            field=models.ManyToManyField(blank=True, null=True, to='messenger.Chat'),
        ),
    ]
