# Generated by Django 3.0.8 on 2020-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0019_auto_20200804_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='9', max_length=100),
        ),
    ]
