# Generated by Django 3.0.8 on 2020-08-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0020_transaction_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Chat',
        ),
    ]
