# Generated by Django 3.0.8 on 2020-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0021_remove_transaction_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
