# Generated by Django 3.1 on 2020-08-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('middleware', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importance', models.SmallIntegerField(default=0)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('Seen', models.BooleanField(default=False)),
                ('Transaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='middleware.transaction')),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.userdetails')),
            ],
        ),
    ]
