# Generated by Django 3.0.8 on 2020-08-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0017_auto_20200803_1319'),
        ('user', '0008_delete_notifications'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Importance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='Seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.UserDetails'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Replays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.Chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='middleware.Transaction'),
        ),
    ]
