# Generated by Django 3.0.8 on 2020-08-03 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200803_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
