# Generated by Django 3.0.8 on 2020-08-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_chat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Replays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.Chat'),
        ),
    ]
