# Generated by Django 3.0.8 on 2020-08-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20200803_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='Replays',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='Subject',
        ),
    ]
