# Generated by Django 3.0.8 on 2020-08-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20200803_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='Text',
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Chat')),
            ],
        ),
    ]
