# Generated by Django 3.0.8 on 2020-08-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20200803_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='ChadBody',
        ),
    ]
