# Generated by Django 3.0.8 on 2020-08-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20200803_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='Seen',
        ),
        migrations.DeleteModel(
            name='ChadBody',
        ),
        migrations.AddField(
            model_name='chatbody',
            name='Chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Chat'),
        ),
    ]
