# Generated by Django 3.0.8 on 2020-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_auto_20200803_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatBody',
        ),
    ]
