# Generated by Django 3.1 on 2020-08-08 17:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=20)),
                ('District', models.CharField(default=None, max_length=20)),
                ('Street', models.CharField(default=None, max_length=20)),
                ('City', models.CharField(default=None, max_length=10)),
                ('zip', models.IntegerField(default=6660)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(default='+8801796693300', max_length=128, region=None, unique=True)),
                ('ACT', models.BooleanField(default=True)),
                ('Password', models.CharField(default=None, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='0', max_length=256, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
            ],
        ),
    ]
