# Generated by Django 3.0.8 on 2020-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First name', models.CharField(default=None, max_length=20)),
                ('Last name', models.CharField(default=None, max_length=20)),
                ('District', models.CharField(default=None, max_length=10)),
                ('Upzila', models.CharField(default=None, max_length=10)),
                ('Email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ACT', models.BooleanField(default=True)),
                ('Password', models.CharField(default=None, max_length=16)),
            ],
        ),
    ]
