# Generated by Django 3.0.8 on 2020-08-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200730_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Email',
        ),
    ]
