# Generated by Django 3.0.8 on 2020-08-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails')),
            ],
        ),
    ]
