# Generated by Django 3.0.8 on 2020-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Importance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifications',
            name='Seen',
            field=models.BooleanField(default=False),
        ),
    ]
