# Generated by Django 3.0.8 on 2020-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200801_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
